### PR TITLE
Instanced mesh

### PR DESCRIPTION
**Pull request by puckey**
This pull request adds support for instance colors to InstancedMesh.

It introduces a new attribute called 'instanceColor'.

I wonder now though if it isn't possible to simply use the existing 'color' attribute instead. Hmm!

### CODE REVIEW

**Comment by pailhead** [comment]
Sorry this took a minute. This is not the right way of doing this i think. You tapped into the vertex colors which shouldn't be overridden by the instance colors. I think that instance colors should replace the color uniform of the material. The vColor should get filled with the vertex color attribute. This, along with a possible texture should be modulated/tinted by the instance color, the same way a material per instance would.

**Comment by puckey** [comment]
Ahh I had an inkling I wasn't doing it in the right way. So we would have to change the color uniform into an attribute? Or add an attribute and override the color uniform instead?

**Comment by pailhead** [comment]
I think combine the two, the same way we use the mesh transformation along with the per instance transformation we could multiply the "global" color uniform with the instance color.

**Comment by puckey** [comment]
Sounds good - I will have another look at this next week.

**Comment by puckey** [comment]
Because an attribute can not be read in the fragment shader, I now pass the instanceColor from the vertex shader to the fragment shader through `varying vec3 vInstanceColor`, where the global color uniform (diffuse) is multiplied by it. Let me know what you think.

**Comment by pailhead** [comment]
Hey, i ended up doing this in `InstancedMesh-dev` before i figured out what's going on. The shader stuff is exactly what it should be, the only thing i did different is only create the color buffer if the flag is set and i made a normalized `Uint8Array` for the color instead of a `Float32`.

**Comment by pailhead** [comment]
Oh i also tried to optimize the quat matrix stuff:

https://stackoverflow.com/questions/43825986/glsl-vector-addition-vs-multiple-floats

I grouped the rows so that they can be multiplied three at a time, and grouped (but unfortunately obfuscated) some of the quat stuff ( `quat x 2` and various component multiplications ). If i understand this correctly it takes out 16 multiplications.

**Pull request closed without merging**
